### ISSUE TITLE
Good job!

### ISSUE THREAD

**Issue by DidntPot** [Zinkil-YT/Pandaz-Core#1]
Alright my guy, I'll stop you right there. Literally vasar core and you're claiming that its yours. Atleast give warro credit. He made this whole core by himself ( some stuff is skidded I know ). LIKE ITS ANNOYING STOP CLAIMING THAT ITS YOURS HOLY SHIT ATLEAST GIVE CREDIT FATTY OMG [ORIGINAL VASAR CORE](https://github.com/Wqrro/Vasar)

**Comment by Zinkil-YT** [comment]
hmmm well vasar used zehox codes and say i'm stealing xddddd

**Comment by DidntPot** [comment]
![image](https://user-images.githubusercontent.com/79522460/123818305-5871f980-d8a5-11eb-8320-254d8400299c.png)

**Comment by DidntPot** [comment]
good job.
